# API Config

OPENAI_API_KEY = ''
PINECONE_API_KEY = ''
PINECONE_INDEX = 'unidosus-edai-hsdemocracy'
PINECONE_ENV = 'us-east-1-aws'
KENDRA_INDEX = ''
AWS_BEDROCK_REGION = 'us-east-1'
AWS_KENDRA_REGION = 'us-east-1'

# AWS config

[default]
# aws keys
aws_access_key_id = ''
aws_secret_access_key = ''
region = 'us-east-1'
